# Generated by Django 6.1.1 on 2026-09-18 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Waiting to start"),
                            (1, "Generating the file"),
                            (5, "File generated"),
                            (9, "File generation failed"),
                            (10, "File in the trash"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True, verbose_name="requested at")),
                (
                    "generation_started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="generation started at"),
                ),
                (
                    "generation_finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="generation finished at"),
                ),
                ("failed_at", models.DateTimeField(blank=True, null=True, verbose_name="failed at")),
                ("trashed_at", models.DateTimeField(blank=True, null=True, verbose_name="trashed at")),
                ("kind", models.CharField(max_length=255, verbose_name="kind of export")),
                ("name", models.CharField(max_length=255, verbose_name="file name")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="notes")),
                (
                    "validation_code",
                    models.CharField(editable=False, max_length=64, unique=True, verbose_name="validation code"),
                ),
                ("storage_key", models.CharField(blank=True, default="", max_length=1024, verbose_name="storage key")),
                (
                    "content_type",
                    models.CharField(default="application/octet-stream", max_length=255, verbose_name="content type"),
                ),
                ("size", models.BigIntegerField(default=0, verbose_name="size (bytes)")),
                ("processing_time", models.IntegerField(default=0, verbose_name="processing time (seconds)")),
                ("upload_time", models.IntegerField(default=0, verbose_name="upload time (seconds)")),
                (
                    "task_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="task id"),
                ),
                ("failure_cause", models.TextField(blank=True, null=True, verbose_name="failure cause")),
                ("failure_stack", models.TextField(blank=True, null=True, verbose_name="failure stack")),
                ("filetype", models.CharField(blank=True, max_length=50, null=True, verbose_name="file format")),
            ],
            options={
                "verbose_name": "exported file",
                "verbose_name_plural": "exported files",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportStakeholder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[(1, "Requester"), (2, "Recipient"), (3, "Manager")], verbose_name="role"
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True, verbose_name="assigned at")),
                (
                    "exported_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stakeholders",
                        to="flat_file_exporter.exportedfile",
                        verbose_name="exported file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="user"
                    ),
                ),
            ],
            options={
                "verbose_name": "stakeholder",
                "verbose_name_plural": "stakeholders",
            },
        ),
    ]
